### ISSUE TITLE
Future OpenIdConnect.authorizeInteractive directly returns null for response when param 'useWebPopup' is false

### ISSUE THREAD

**Issue by WilkoThomassen** [4D-Technologies/openidconnect_flutter#44]
This behaviour can be reproduced in the Example project using 'Interactive Authorization Code PKCE' option. 
Choose to have no popup for logging in. 

The following code in the example directly returns null when the Login screen is displayed

```
final response = await OpenIdConnect.authorizeInteractive(
                        context: context,
                        title: "Login",
                        request: await InteractiveAuthorizationRequest.create(
                          clientId: defaultClientId,
                          clientSecret: defaultClientSecret,
                          redirectUrl: defaultRedirectUrl,
                          scopes: defaultscopes,
                          configuration: discoveryDocument!,
                          autoRefresh: false,
                          useWebPopup: usePopup,
                        ),
```
                        
Beneath the surface the token is properly set after loggin in with the form because when I reload the webapp and run the method a second time, then a valid authresponse is returned.

It all works perfectly fine when I use the popup window, the future is then properly awaited and returns a valid authresponse after logging in.

**Comment by markbeij** [comment]
I experience the same, @ahmednfwela can you tell if this is a bug or by design?
What is the expected behavior?

**Comment by ahmednfwela** [comment]
can you try referencing the latest version of the package on main branch? since it hasn't been published yet by @jhancock4d

**Comment by WilkoThomassen** [comment]
> 

I reproduced it on the latest version of the package on the main branch.

**Comment by ahmednfwela** [comment]
using these references:
```yaml
  openidconnect:
    git:
      url: git@github.com:4D-Technologies/openidconnect_flutter.git
      ref: main
      path: openidconnect
  openidconnect_web:
    git:
      url: git@github.com:4D-Technologies/openidconnect_flutter.git
      ref: main
      path: openidconnect_web
  openidconnect_platform_interface:
    git:
      url: git@github.com:4D-Technologies/openidconnect_flutter.git
      ref: main
      path: openidconnect_platform_interface
```
this client:
```dart
client = await OpenIdConnectClient.create(
  discoveryDocumentUrl:
      'https://somewebsite.com/.well-known/openid-configuration',
  redirectUrl: 'http://localhost:4200/callback.html',
  clientId: 'SomeClientId',
  audiences: ['SomeAudience'],
  scopes: ['openid', 'SomeScopes'],
  autoRefresh: true,
);
```
this request:
```dart
final identity = await client.loginInteractive(
  context: context,
  title: "Login",
  useWebPopup: true,
);
```

has been tested and currently is deployed on a production environment
